### ISSUE TITLE
Wrong plugin id

### ISSUE THREAD

**Issue by biesbjerg** [phuongwd/cordova-plugin-audio-background-mode#1]
Name of the plugin is `cordova-plugin-audio-background-mode`.

In plugin.xml the id is specified as `cordova-plugin-audio-background-modes` (`mode` vs `modes`).
https://github.com/phuongwd/cordova-plugin-audio-background-mode/blob/master/plugin.xml#L3

This is not a huge issue, but it causes some confusion/weird looking keys in package.json (at least in Cordova 7.0) since the dependency is named `cordova-plugin-audio-background-mode` but the key for configuration is called `cordova-plugin-audio-background-modes`.

Example:

```
...
    "dependencies": {
        "cordova-plugin-audio-background-mode": "file:node_modules/cordova-plugin-audio-background-mode"
    },
    "cordova": {
        "platforms": [
            "android",
            "browser",
            "ios"
        ],
        "plugins": {
            "cordova-plugin-ios-localized-strings": {
                "MAIN_LANGUAGE": "English",
                "ADDITIONAL_LANGUAGES": "da,sv,no,fi,de-DE,nl-NL"
            },
            "cordova-plugin-audio-background-modes": {}
        }
    }
...
```

**Comment by phuongwd** [comment]
Thank you,
[Resolved](https://github.com/phuongwd/cordova-plugin-audio-background-mode/commit/9ef530327064c75aef0915b46c341c0e15ae5914)

**Comment by inidona** [comment]
Hi, when will the 0.0.2 via npm released ?
